# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85fa1cdd9993ea9820a88993f56854f7071f9b63cdda615c6c366e407dfb3933beed8570fd3e497fd32ab79bd1d958cda01135f6a78ef1cf04a9b4b2c5af0fcf

test:
  secret_key_base: 70bf6100f606ecb694860745b57b915ce9b1425f5dff5f5e9e2420f8275d7e43d5497eaac84697ea53fa17dfc7bcf2a578e93697015871e3563b176136e7a8de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
